"""Auto-generated by LLM pipeline. Version 2. 2026-05-14T18:55:31.696350"""

import torch

def sample_failure_episode_config(b: int, device: torch.device) -> tuple[torch.Tensor, torch.Tensor]:
    """
    Args:
        b: batch size (number of parallel environments)
        device: torch device
    Returns:
        positions: (b, 3) tensor of T-block initial positions
        quaternions: (b, 4) tensor of T-block initial orientations [w, x, y, z]
    """
    # Goal position and constants
    goal_x, goal_y = -0.156, -0.1
    block_length = 0.1  # Approximate T-block length
    failure_distance = 0.5 * block_length  # ~0.05m
    
    # Determine which samples are failure vs random (70% failure, 30% random)
    is_failure = torch.rand(b, device=device) < 0.7
    n_failure = is_failure.sum().item()
    n_random = b - n_failure
    
    # Initialize position tensor
    positions = torch.zeros(b, 3, device=device)
    positions[:, 2] = 0.021  # Fixed z position
    
    # Sample failure regime positions (CoM displaced by ~0.5 * block_length from goal)
    if n_failure > 0:
        # Sample angles uniformly around goal position
        angles = torch.rand(n_failure, device=device) * 2 * torch.pi
        # Sample distances around failure_distance with some variation
        distances = failure_distance + torch.randn(n_failure, device=device) * 0.01
        distances = torch.clamp(distances, 0.04, 0.08)  # Keep within reasonable bounds
        
        failure_x = goal_x + distances * torch.cos(angles)
        failure_y = goal_y + distances * torch.sin(angles)
        
        # Clamp to workspace bounds
        failure_x = torch.clamp(failure_x, -0.356, -0.056)
        failure_y = torch.clamp(failure_y, -0.3, 0.2)
        
        positions[is_failure, 0] = failure_x
        positions[is_failure, 1] = failure_y
    
    # Sample random positions for diversity
    if n_random > 0:
        random_x = goal_x + (torch.rand(n_random, device=device) - 0.5) * 0.2
        random_y = goal_y + (torch.rand(n_random, device=device) - 0.5) * 0.6 + 0.05
        
        # Clamp to workspace bounds
        random_x = torch.clamp(random_x, -0.356, -0.056)
        random_y = torch.clamp(random_y, -0.3, 0.2)
        
        positions[~is_failure, 0] = random_x
        positions[~is_failure, 1] = random_y
    
    # Sample orientations (Z-rotation only)
    z_rotations = torch.rand(b, device=device) * 2 * torch.pi
    
    # Convert to quaternions [w, x, y, z] for Z-rotation only
    half_angles = z_rotations / 2
    quaternions = torch.zeros(b, 4, device=device)
    quaternions[:, 0] = torch.cos(half_angles)  # w
    quaternions[:, 1] = 0.0  # x
    quaternions[:, 2] = 0.0  # y
    quaternions[:, 3] = torch.sin(half_angles)  # z
    
    return positions, quaternions