"""Auto-generated by LLM pipeline. Version 1. 2026-05-14T19:11:47.791906"""

import torch

def compute_dense_reward(self, obs, action, info):
    # Calculate T-block center of mass position (accounting for offset)
    tee_z_eulers = self.quat_to_z_euler(self.tee.pose.q)
    cos_angle = torch.cos(tee_z_eulers)
    sin_angle = torch.sin(tee_z_eulers)
    
    # CoM offset in world coordinates: (0, 0.0375) rotated by current angle
    com_offset_x = -0.0375 * sin_angle  # negative because y offset becomes -x when rotated
    com_offset_y = 0.0375 * cos_angle
    
    tee_com_pos = self.tee.pose.p.clone()
    tee_com_pos[:, 0] += com_offset_x
    tee_com_pos[:, 1] += com_offset_y
    
    # Goal CoM position (accounting for goal rotation)
    goal_cos = torch.cos(torch.tensor(self.goal_z_rot, device=self.device))
    goal_sin = torch.sin(torch.tensor(self.goal_z_rot, device=self.device))
    goal_com_offset_x = -0.0375 * goal_sin
    goal_com_offset_y = 0.0375 * goal_cos
    
    goal_com_pos = self.goal_tee.pose.p.clone()
    goal_com_pos[:, 0] += goal_com_offset_x
    goal_com_pos[:, 1] += goal_com_offset_y
    
    # 1. Rotation reward (0.4 weight)
    rot_error = torch.abs(tee_z_eulers - self.goal_z_rot)
    rot_error = torch.min(rot_error, 2 * torch.pi - rot_error)  # Handle angle wrapping
    rot_rew = torch.exp(-2.0 * rot_error)
    
    # 2. Center of Mass position reward (0.6 weight) - critical for addressing failure mode
    com_to_goal = tee_com_pos[:, :2] - goal_com_pos[:, :2]
    com_dist = torch.linalg.norm(com_to_goal, dim=1)
    com_rew = torch.exp(-8.0 * com_dist)
    
    # 3. Block position reward (0.4 weight) - for general positioning
    tee_to_goal_pose = self.tee.pose.p[:, :2] - self.goal_tee.pose.p[:, :2]
    tee_to_goal_dist = torch.linalg.norm(tee_to_goal_pose, dim=1)
    pos_rew = torch.exp(-5.0 * tee_to_goal_dist)
    
    # 4. End-effector guidance (0.3 weight) - encourage contact with block
    tcp_to_tee = self.tee.pose.p - self.agent.tcp.pose.p
    tcp_to_tee_dist = torch.linalg.norm(tcp_to_tee, dim=1)
    tcp_rew = torch.exp(-3.0 * tcp_to_tee_dist)
    
    # 5. Strategic pushing reward - encourage pushing from correct side for rotation
    # Vector from CoM to goal CoM
    com_to_goal_vec = goal_com_pos[:, :2] - tee_com_pos[:, :2]
    com_to_goal_norm = torch.linalg.norm(com_to_goal_vec, dim=1, keepdim=True)
    com_to_goal_unit = com_to_goal_vec / (com_to_goal_norm + 1e-6)
    
    # Vector from TCP to CoM
    tcp_to_com = tee_com_pos[:, :2] - self.agent.tcp.pose.p[:, :2]
    tcp_to_com_norm = torch.linalg.norm(tcp_to_com, dim=1, keepdim=True)
    tcp_to_com_unit = tcp_to_com / (tcp_to_com_norm + 1e-6)
    
    # Reward alignment between push direction and desired CoM movement
    push_alignment = torch.sum(tcp_to_com_unit * com_to_goal_unit, dim=1)
    push_alignment_rew = (push_alignment + 1.0) / 2.0  # Map from [-1,1] to [0,1]
    
    # Combine rewards with weights that sum to 2.0 for non-success cases
    reward = (0.4 * rot_rew + 
              0.6 * com_rew + 
              0.4 * pos_rew + 
              0.3 * tcp_rew + 
              0.3 * push_alignment_rew)
    
    # Success bonus
    reward[info["success"]] = 3.0
    
    return reward