"""LLM pipeline: video -> frames -> prompt -> LLM -> code -> validate -> save.

Uses OpenRouter (OpenAI-compatible API) via the `openai` Python SDK.
Set the OPENROUTER_API_KEY environment variable before running.
"""

import os
import re
import time
from datetime import datetime
from pathlib import Path

from openai import OpenAI

from llm_reward_gen.prompts import (
    EPISODE_CONFIG_SYSTEM_PROMPT,
    REWARD_SYSTEM_PROMPT,
    build_episode_config_prompt,
    build_refinement_prompt,
    build_reward_prompt,
)
from llm_reward_gen.video_analysis import extract_frames, frames_to_base64

GENERATED_DIR = Path(__file__).parent / "generated"
DOCS_DIR = Path(__file__).parent / "docs"


def _parse_code_from_response(response_text: str) -> str:
    """Extract Python code from between ```python ... ``` fences."""
    pattern = r"```python\s*\n(.*?)```"
    matches = re.findall(pattern, response_text, re.DOTALL)
    if not matches:
        pattern = r"```\s*\n(.*?)```"
        matches = re.findall(pattern, response_text, re.DOTALL)
    if not matches:
        raise ValueError("No code block found in LLM response")
    return matches[0].strip()


def _build_vision_messages(
    user_prompt: str, frame_b64_list: list[str]
) -> list[dict]:
    """Build the message content array with text and base64 images.

    Uses the OpenAI image_url format (data URI), which OpenRouter accepts for
    all vision-capable models (Claude, GPT-4o, Gemini, etc.).
    """
    content: list[dict] = [{"type": "text", "text": user_prompt}]
    for b64 in frame_b64_list:
        content.append(
            {
                "type": "image_url",
                "image_url": {"url": f"data:image/png;base64,{b64}"},
            }
        )
    return content


def _call_llm(
    system_prompt: str,
    user_content: list[dict],
    model: str = "anthropic/claude-sonnet-4",
    temperature: float = 0.2,
    max_tokens: int = 4096,
) -> str:
    """Call OpenRouter API and return the text response.

    Reads OPENROUTER_API_KEY from the environment.
    Model strings follow OpenRouter's format: "provider/model-name".
    Examples:
        "anthropic/claude-sonnet-4"
        "anthropic/claude-opus-4"
        "openai/gpt-4o"
        "google/gemini-2.0-flash-001"
    """
    api_key = os.environ.get("OPENROUTER_API_KEY")
    if not api_key:
        raise EnvironmentError(
            "OPENROUTER_API_KEY environment variable is not set. "
            "Get a key at https://openrouter.ai/keys and export it:\n"
            "  export OPENROUTER_API_KEY='sk-or-...'"
        )
    client = OpenAI(
        api_key=api_key,
        base_url="https://openrouter.ai/api/v1",
    )
    response = client.chat.completions.create(
        model=model,
        max_tokens=max_tokens,
        temperature=temperature,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_content},
        ],
    )
    return response.choices[0].message.content


def _save_code(code: str, name: str, version: int) -> Path:
    """Write generated code to the generated/ directory."""
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    filename = f"{name}_v{version:03d}.py"
    path = GENERATED_DIR / filename
    header = f'"""Auto-generated by LLM pipeline. Version {version}. {datetime.now().isoformat()}"""\n\nimport torch\n\n'
    path.write_text(header + code)
    return path


def _log_prompt(
    failure_mode: str,
    artifact_type: str,
    prompt_text: str,
    response_text: str,
    model: str,
    temperature: float,
    validation_result: str,
    attempt: int,
    accepted: bool,
):
    """Append an entry to docs/prompts_log.md."""
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    log_path = DOCS_DIR / "prompts_log.md"
    entry = f"""
---
### {artifact_type} | {failure_mode} | Attempt {attempt} | {datetime.now().isoformat()}
**Model**: {model}, temperature={temperature}
**Accepted**: {accepted}
**Validation**: {validation_result}

<details>
<summary>Prompt (click to expand)</summary>

```
{prompt_text[:2000]}{'...[truncated]' if len(prompt_text) > 2000 else ''}
```
</details>

<details>
<summary>Response (click to expand)</summary>

```python
{response_text[:3000]}{'...[truncated]' if len(response_text) > 3000 else ''}
```
</details>
"""
    with open(log_path, "a") as f:
        f.write(entry)


def generate_reward_function(
    video_path: str,
    failure_mode: str,
    failure_description: str,
    quantitative_chars: list[str],
    baseline_success_rate: float = 60.0,
    model: str = "anthropic/claude-sonnet-4",
    temperature: float = 0.2,
    num_frames: int = 8,
    max_retries: int = 3,
    validate_fn=None,
) -> Path:
    """Generate a reward function from a failure mode video.

    Args:
        video_path: Path to mp4 video of the failure.
        failure_mode: Short name (e.g., "rotation_failure").
        failure_description: Qualitative description of the failure.
        quantitative_chars: List of quantitative characterization strings.
        baseline_success_rate: Success rate of baseline policy.
        model: Anthropic model to use.
        temperature: Sampling temperature.
        num_frames: Number of frames to extract from video.
        max_retries: Maximum refinement attempts.
        validate_fn: Optional callable(code_path) -> (bool, str) for validation.

    Returns:
        Path to the saved reward function file.
    """
    frames = extract_frames(video_path, num_frames)
    frame_b64s = frames_to_base64(frames)

    user_prompt = build_reward_prompt(
        failure_mode_name=failure_mode,
        failure_mode_description=failure_description,
        quantitative_chars=quantitative_chars,
        baseline_success_rate=baseline_success_rate,
        num_frames=num_frames,
    )

    user_content = _build_vision_messages(user_prompt, frame_b64s)

    for attempt in range(1, max_retries + 1):
        print(f"  [Reward] Attempt {attempt}/{max_retries} for {failure_mode}...")
        response_text = _call_llm(
            REWARD_SYSTEM_PROMPT, user_content, model=model, temperature=temperature
        )
        try:
            code = _parse_code_from_response(response_text)
        except ValueError as e:
            _log_prompt(
                failure_mode, "reward", user_prompt, response_text,
                model, temperature, f"PARSE ERROR: {e}", attempt, False,
            )
            continue

        code_path = _save_code(code, f"reward_{failure_mode}", attempt)

        if validate_fn is not None:
            passed, validation_msg = validate_fn(str(code_path))
            _log_prompt(
                failure_mode, "reward", user_prompt, code,
                model, temperature, validation_msg, attempt, passed,
            )
            if passed:
                print(f"  [Reward] Accepted on attempt {attempt}")
                return code_path
            else:
                print(f"  [Reward] Validation failed: {validation_msg}")
                refinement_prompt = build_refinement_prompt(
                    artifact_type="reward function",
                    error_message=validation_msg,
                    statistics="See error above",
                    previous_code=code,
                )
                user_content = [{"type": "text", "text": refinement_prompt}]
        else:
            _log_prompt(
                failure_mode, "reward", user_prompt, code,
                model, temperature, "no validation", attempt, True,
            )
            print(f"  [Reward] Saved (no validation) on attempt {attempt}")
            return code_path

    print(f"  [Reward] All {max_retries} attempts failed for {failure_mode}")
    return code_path


def generate_episode_config(
    video_path: str,
    failure_mode: str,
    failure_description: str,
    quantitative_chars: list[str],
    model: str = "anthropic/claude-sonnet-4",
    temperature: float = 0.2,
    num_frames: int = 8,
    max_retries: int = 3,
    validate_fn=None,
) -> Path:
    """Generate an episode configuration sampler from a failure mode video.

    Args:
        video_path: Path to mp4 video of the failure.
        failure_mode: Short name (e.g., "rotation_failure").
        failure_description: Qualitative description of the failure.
        quantitative_chars: List of quantitative characterization strings.
        model: Anthropic model to use.
        temperature: Sampling temperature.
        num_frames: Number of frames to extract from video.
        max_retries: Maximum refinement attempts.
        validate_fn: Optional callable(code_path) -> (bool, str) for validation.

    Returns:
        Path to the saved episode config file.
    """
    frames = extract_frames(video_path, num_frames)
    frame_b64s = frames_to_base64(frames)

    user_prompt = build_episode_config_prompt(
        failure_mode_name=failure_mode,
        failure_mode_description=failure_description,
        quantitative_chars=quantitative_chars,
    )

    user_content = _build_vision_messages(user_prompt, frame_b64s)

    for attempt in range(1, max_retries + 1):
        print(f"  [EpisodeConfig] Attempt {attempt}/{max_retries} for {failure_mode}...")
        response_text = _call_llm(
            EPISODE_CONFIG_SYSTEM_PROMPT,
            user_content,
            model=model,
            temperature=temperature,
        )
        try:
            code = _parse_code_from_response(response_text)
        except ValueError as e:
            _log_prompt(
                failure_mode, "episode_config", user_prompt, response_text,
                model, temperature, f"PARSE ERROR: {e}", attempt, False,
            )
            continue

        code_path = _save_code(code, f"episode_config_{failure_mode}", attempt)

        if validate_fn is not None:
            passed, validation_msg = validate_fn(str(code_path))
            _log_prompt(
                failure_mode, "episode_config", user_prompt, code,
                model, temperature, validation_msg, attempt, passed,
            )
            if passed:
                print(f"  [EpisodeConfig] Accepted on attempt {attempt}")
                return code_path
            else:
                print(f"  [EpisodeConfig] Validation failed: {validation_msg}")
                refinement_prompt = build_refinement_prompt(
                    artifact_type="episode configuration sampler",
                    error_message=validation_msg,
                    statistics="See error above",
                    previous_code=code,
                )
                user_content = [{"type": "text", "text": refinement_prompt}]
        else:
            _log_prompt(
                failure_mode, "episode_config", user_prompt, code,
                model, temperature, "no validation", attempt, True,
            )
            print(f"  [EpisodeConfig] Saved (no validation) on attempt {attempt}")
            return code_path

    print(f"  [EpisodeConfig] All {max_retries} attempts failed for {failure_mode}")
    return code_path
